### PR TITLE
ImageButton position and size

### PR DESCRIPTION
**Pull request by MetalDent**

### CODE REVIEW

**Review by se6astian-pi — COMMENTED** [review]
MetalDent would you be so kind and move as many position/dimension calculations from the draw() function to the constructor.

**Comment by MetalDent** [comment]
> MetalDent would you be so kind and move as many position/dimension calculations from the draw() function to the constructor.

But all the calculations are using `IPainter* painter` which is not defined in the constructor and but in the Draw()

**Comment by BAndiT1983** [comment]
Start with ButtonBar first and simplify the code there first.

**Comment by MetalDent** [comment]
> Start with ButtonBar first and simplify the code there first.

You mean simplify the SetButton() ?

**Comment by BAndiT1983** [comment]
Yes, as there are calculations which can be done only one time.

**Comment by MetalDent** [comment]
> Yes, as there are calculations which can be done only one time.

Okay!

**Comment by BAndiT1983** [comment]
Diff shows empty files, is something wrong?

**Comment by se6astian-pi** [comment]
Firmware/UI/Widgets/ToggleButton.h 100644 → 100755 

means just permissions changed correct?

**Pull request closed without merging**
