### PR TITLE
Task T1193 (adding checkbox  element)

### PR DESCRIPTION
**Pull request by eppisai**
After clicking on the menu button, there are  certain true and false option, the checkbox was needed there, so have added a checkbox element as mentioned in the task.

In the comments of the Task T1193 it was written to make draw function in checkboxmenutime.h on line 43. So have placed a conditional statement, on line 43 of checkboxmenuitem.h, and have included two header files (checkboxtrue_icon.h, checkboxfalse_icon.h).So, where ever checkboxmenitem.h will be imported, then checkbox will appear

Below is the video of how the checkbox looks in the menu.

https://user-images.githubusercontent.com/54789531/103020612-bf1d0000-456e-11eb-9566-c41b178acc67.mp4

### CODE REVIEW

**Comment by BAndiT1983** [comment]
Great! Preview looks nice. Will check the code soon.

**Comment by BAndiT1983** [comment]
Really small solution, looks nice. But please avoid ternary for full drawing, as it bloats the code. Just use it to exchange the image in a separate variable and assign it to draw method.

**Comment by eppisai** [comment]
> Really small solution, looks nice. But please avoid ternary for full drawing, as it bloats the code. Just use it to exchange the image in a separate variable and assign it to draw method.

ohk, I understand what you are saying..

**Comment by eppisai** [comment]
```
        auto checkbox = (_checkboxValue) ? checkboxtrue_icon : checkboxfalse_icon;
        painter->DrawIcon(&checkbox, _x + 235 , _y + _verticalLabelOffset - 17, _currentTextColor);
```

LIke this? @BAndiT1983

**Comment by BAndiT1983** [comment]
Yep, looks good, merging. But please avoid unnecessary empty lines. One of important things of software development is to keep constant code layout.

**Comment by eppisai** [comment]
> Yep, looks good, merging. But please avoid unnecessary empty lines. One of important things of software development is to keep constant code layout.

oh.. I keep this in mind from now on..

**Comment by se6astian-pi** [comment]
Very nice, thanks or the contribution!

**Pull request merged**
